
export const featureStyles = {
  card: {
    width: "100%",
    height: { xs: "250px", sm: "300px", md: "353px" },
    position: "relative",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    textAlign: "center",
    boxShadow: "none",
    bgcolor: "transparent",
    borderRadius: '30px',
    perspective: '1000px',
    cursor: 'pointer',
    '&:hover': {
      '& .flip-icon': {
        opacity: 1,
      },
      '& .card-inner': {
        boxShadow: '0 0 15px rgba(0, 0, 0, 0.3)',
      },
    },
  },
  cardInner: {
    position: 'relative',
    width: '100%',
    height: '100%',
    transition: 'transform 0.6s, box-shadow 0.3s',
    transformStyle: 'preserve-3d',
  },
  cardFace: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backfaceVisibility: 'hidden',
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  cardContent: {
    position: "absolute",
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    color: "#fff",
    backgroundColor: "rgba(0, 0, 0, 0.5)", 
    padding: { xs: "15px", sm: "20px", md: "40px" },
    borderRadius: "8px",
  },
  heading: {
    fontFamily: "Roboto",
    fontSize: { xs: "20px", sm: "24px", md: "30px" },
    fontWeight: "bold",
    lineHeight: { xs: "1.2", md: "1.6" },
    fontStyle: "italic",
    textAlign: 'center',
  },
  flipIcon: {
    opacity: 0,
    transition: 'opacity 0.3s',
    display: 'flex',
    alignItems: 'center',
    mt: 2,
  },
  cardBack: {
    position: "absolute",
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    transform: 'rotateY(180deg)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: "#fff",
    backgroundColor: "rgba(0, 0, 0, 0.8)", 
    padding: { xs: "15px", sm: "20px", md: "40px" },
    borderRadius: "8px",
  },
  description: {
    fontFamily: "Roboto",
    fontSize: { xs: "14px", sm: "16px", md: "20px" },
    fontWeight: "bold",
    lineHeight: "1.2",
  },
  featuresBox: {
    bgcolor: "background.default",
    py: { xs: 4, md: 8 },
  },
  featuresHeading: {
    fontFamily: "Playfair Display",
    fontSize: { xs: "28px", sm: "36px", md: "54px" },
    fontStyle: "italic",
    fontWeight: 900,
    lineHeight: { xs: "1.2", md: "1.3" },
    color: "#000000",
  },
  featuresDescription: {
    fontFamily: "Roboto",
    fontSize: { xs: "16px", sm: "18px", md: "24px" },
    width: "100%",
    maxWidth: "1128px",
    margin: "0 auto",
    color: "#000000",
    fontWeight: "bold",
    mb: { xs: 3, md: 5 },
  },
};